class FooterLocators(object):

    newsletter_input = '//*[@id="newsletter-input"]'
    newsletter_submit = '//*[@id="newsletter_block_left"]/div/form/div/button'
    facebook = '//*[@id="social_block"]/ul/li[1]/a'
    twitter = '//*[@id="social_block"]/ul/li[2]/a'
    youtube = '//*[@id="social_block"]/ul/li[3]/a'
    google_plus = '//*[@id="social_block"]/ul/li[4]/a'
    women = '//*[@id="footer"]/div/section[2]/div/div/ul/li/a'
    specials = '//*[@id="block_various_links_footer"]/ul/li[1]/a'
    new_products = '//*[@id="block_various_links_footer"]/ul/li[2]/a'
    best_sellers = '//*[@id="block_various_links_footer"]/ul/li[3]/a'
    our_stores = '//*[@id="block_various_links_footer"]/ul/li[4]/a'
    contact_us = '//*[@id="block_various_links_footer"]/ul/li[5]/a'
    terms_and_conditions_of_use = '//*[@id="block_various_links_footer"]/ul/li[6]/a'
    about_us = '//*[@id="block_various_links_footer"]/ul/li[7]/a'
    sitemap = '//*[@id="block_various_links_footer"]/ul/li[8]/a'
    my_account = '//*[@id="footer"]/div/section[5]/h4/a'
    my_orders = '//*[@id="footer"]/div/section[5]/div/ul/li[1]/a'
    my_credit_slips = '//*[@id="footer"]/div/section[5]/div/ul/li[2]/a'
    my_addresses = '//*[@id="footer"]/div/section[5]/div/ul/li[3]/a'
    my_personal_info = '//*[@id="footer"]/div/section[5]/div/ul/li[4]/a'
    email = '//*[@id="block_contact_infos"]/div/ul/li[3]/span/a'
    phone_number = '//*[@id="block_contact_infos"]/div/ul/li[2]/span'
    presta_shop = '//*[@id="footer"]/div/section[4]/div/a'
