class URLs(object):
    home_page = 'http://automationpractice.com/index.php'
    search_empty = 'http://automationpractice.com/index.php?controller=search&orderby=position&orderway=desc&search_query=&submit_search='
    cart_empty = 'http://automationpractice.com/index.php?controller=order'
    contact_us = 'http://automationpractice.com/index.php?controller=contact'
    sign_in = 'http://automationpractice.com/index.php?controller=authentication&back=my-account'
    category_women = 'http://automationpractice.com/index.php?id_category=3&controller=category'
    category_dresses = 'http://automationpractice.com/index.php?id_category=8&controller=category'
    category_tshirts = 'http://automationpractice.com/index.php?id_category=5&controller=category'
    category_tops = 'http://automationpractice.com/index.php?id_category=4&controller=category'
    category_blouses = 'http://automationpractice.com/index.php?id_category=7&controller=category'
    category_casual_dresses = 'http://automationpractice.com/index.php?id_category=9&controller=category'
    category_evening_dresses = 'http://automationpractice.com/index.php?id_category=10&controller=category'
    category_summer_dresses = 'http://automationpractice.com/index.php?id_category=11&controller=category'