
URLs = {
    'home_page': 'http://automationpractice.com/index.php',
    'search_empty': 'http://automationpractice.com/index.php?controller=search&orderby=position&orderway=desc&search_query=&submit_search=',
    'cart_empty': 'http://automationpractice.com/index.php?controller=order',
    'contact_us': 'http://automationpractice.com/index.php?controller=contact',
    'sign_in': 'http://automationpractice.com/index.php?controller=authentication&back=my-account',
    'category_women': 'http://automationpractice.com/index.php?id_category=3&controller=category',
    'category_dresses': 'http://automationpractice.com/index.php?id_category=8&controller=category',
    'category_tshirts': 'http://automationpractice.com/index.php?id_category=5&controller=category',
    'category_tops': 'http://automationpractice.com/index.php?id_category=4&controller=category',
    'category_blouses': 'http://automationpractice.com/index.php?id_category=7&controller=category',
    'category_casual_dresses': 'http://automationpractice.com/index.php?id_category=9&controller=category',
    'category_evening_dresses': 'http://automationpractice.com/index.php?id_category=10&controller=category',
    'category_summer_dresses': 'http://automationpractice.com/index.php?id_category=11&controller=category',
    'search_dress': 'http://automationpractice.com/index.php?controller=search&orderby=position&orderway=desc&search_query=dress&submit_search=',

    'facebook': 'https://www.facebook.com/groups/525066904174158/',
    'twitter': 'https://twitter.com/seleniumfrmwrk',
    'youtube': 'https://www.youtube.com/channel/UCHl59sI3SRjQ-qPcTrgt0tA',
    'google_plus': 'https://plus.google.com/111979135243110831526',

    'specials': 'http://automationpractice.com/index.php?controller=prices-drop',
    'new_products': 'http://automationpractice.com/index.php?controller=new-products',
    'best_sellers': 'http://automationpractice.com/index.php?controller=best-sales',
    'our_stores': 'http://automationpractice.com/index.php?controller=stores',
    'contact_us': 'http://automationpractice.com/index.php?controller=contact',
    'terms_and_conditions_of_use': 'http://automationpractice.com/index.php?id_cms=3&controller=cms',
    'about_us': 'http://automationpractice.com/index.php?id_cms=4&controller=cms',
    'sitemap': 'http://automationpractice.com/index.php?controller=sitemap',
    'my_account': 'http://automationpractice.com/index.php?controller=authentication&back=my-account',
    'my_orders': 'http://automationpractice.com/index.php?controller=authentication&back=history',
    'my_credit_slips': 'http://automationpractice.com/index.php?controller=authentication&back=order-slip',
    'my_addresses': 'http://automationpractice.com/index.php?controller=authentication&back=addresses',
    'my_personal_info': 'http://automationpractice.com/index.php?controller=authentication&back=identity',
    'presta_shop': 'https://www.prestashop.com/en'
}
