
header_locators = {
    'banner': {
        'type': 'xpath',
        'locator': '//*[@id="header"]/div[1]/div/div/a/img'},
    'phone_number': {
        'type': 'xpath',
        'locator': '//span[@class="shop-phone"]/strong'},
    'contact_us': {
        'type': 'xpath',
        'locator': '//div[@id="contact-link"]'},
    'sign_in': {
        'type': 'xpath',
        'locator': '//a[@class="login"]'},
    'logo': {
        'type': 'xpath',
        'locator': '//div[@id="header_logo"]/a/img[@class="logo img-responsive"]'},
    'search_input': {
        'type': 'xpath',
        'locator': '//input[@id="search_query_top"]'},
    'search_lup': {
        'type': 'xpath',
        'locator': '//button[@name="submit_search"]'},
    'cart': {
        'type': 'xpath',
        'locator': '//*[@title="View my shopping cart"]'},
    'cat_women': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]'},
    'cat_women_tops': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[1]/a'},
    'cat_women_tshirts': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[1]/ul/li[1]/a'},
    'cat_women_blouses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[1]/ul/li[2]/a'},
    'cat_women_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[2]/a'},
    'cat_women_casual_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[2]/ul/li[1]/a'},
    'cat_women_evening_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[2]/ul/li[2]/a'},
    'cat_women_summer_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[1]/ul/li[2]/ul/li[3]/a'},
    'cat_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[2]'},
    'cat_dresses_casual_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[2]/ul/li[1]/a'},
    'cat_dresses_evening_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[2]/ul/li[2]/a'},
    'cat_dresses_summer_dresses': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[2]/ul/li[3]/a'},
    'cat_tshirts': {
        'type': 'xpath',
        'locator': '//*[@id="block_top_menu"]/ul/li[3]'},
}
