
create_an_account_locators = {
    'radiobox_mr': {
        'type': 'id',
        'locator': 'id_gender1'},
    'radiobox_mrs': {
        'type': 'id',
        'locator': 'id_gender2'},
    'input_first_name': {
        'type': 'id',
        'locator': 'customer_firstname'},
    'input_last_name': {
        'type': 'id',
        'locator': 'customer_lastname'},
    'input_email': {
        'type': 'id',
        'locator': 'email'},
    'input_password': {
        'type': 'id',
        'locator': 'email'},
    'dropdown_brith_day': {
        'type': 'id',
        'locator': 'days'},
    'dropdown_brith_month': {
        'type': "id",
        'locator': 'months'},
    'dropdown_brith_year': {
        'type': 'id',
        'locator': 'years'},
    'checkbox_newsletter': {
        'type': 'id',
        'locator': 'newsletter'},
    'checkbox_special_offers': {
        'type': 'id',
        'locator': 'optin'},
    'input_address_first_name': {
        'type': 'id',
        'locator': 'firstname'},
    'input_address_last_name': {
        'type': 'id',
        'locator': 'lastname'},
    'input_company': {
        'type': 'id',
        'locator': 'company'},
    'input_address_1': {
        'type': 'id',
        'locator': 'address1'},
    'input_address_2': {
        'type': 'id',
        'locator': 'address2'},
    'input_city': {
        'type': 'id',
        'locator': 'city'},
    'dropdown_state': {
        'type': 'id',
        'locator': 'id_state'},
    'input_zip_code': {
        'type': 'id',
        'locator': 'postcode'},
    'dropdown_country': {
        'type': 'id',
        'locator': 'id_country'},
    'input_additional_information': {
        'type': 'id',
        'locator': 'other'},
    'input_home_phone': {
        'type': 'id',
        'locator': 'phone'},
    'input_mobile_phone': {
        'type': 'id',
        'locator': 'phone_mobile'},
    'input_alias_address': {
        'type': 'id',
        'locator': 'alias'},
    'btn_register': {
        'type': 'id',
        'locator': 'submitAccount'},
}

